### PR TITLE
Making compatible with Racket's packaging conventions

### PR DESCRIPTION
**Pull request by christianromney**
Added a miniKanren collection as explained here:
http://docs.racket-lang.org/pkg/Package_Concepts.html

Basically, I just moved the files into a subdirectory which allows me to:
1. raco pkg install github://github.com/xmlblog/Racket-miniKanren/master
2. (require miniKanren/mk)

You can test with my fork if you like, but the idea would be that your repository be directly installable as a Racket package. Cheers!

Signed-off-by: Christian Romney cromney@pointslope.com

### CODE REVIEW

**Comment by christianromney** [comment]
Bump :)

**Comment by miniKanren** [comment]
Merged @christianromney's pull request to update package management

**Comment by miniKanren** [comment]
Sorry about that!  I'm not so good with the GitHubs.  ;)

Thanks for the pull request!

--Will

**Comment by christianromney** [comment]
No worries, it was a trivial change anyway but hopefully one that makes it easy to access via Racket.

**Pull request merged**
